name: word2world
channels:
  - defaults
  - nodefaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.9.5=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.6.0=h6a678d5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=14.0.2=h374c478_1
  - async-timeout=4.0.3=py310h06a4308_0
  - attrs=23.1.0=py310h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=openblas
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py310h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - colorama=0.4.6=py310h06a4308_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - datasets=2.12.0=py310h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - dill=0.3.6=py310h06a4308_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - filelock=3.13.1=py310h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py310h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py310h5eee18b_0
  - fsspec=2024.3.1=py310h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py310h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - grpc-cpp=1.48.2=he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - huggingface_hub=0.23.1=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - imagecodecs=2023.1.23=py310hc4b7b5f_0
  - imageio=2.33.1=py310h06a4308_0
  - joblib=1.4.0=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy_loader=0.3=py310h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.8.4=py310h06a4308_0
  - matplotlib-base=3.8.4=py310h1128e8f_0
  - multidict=6.0.4=py310h5eee18b_0
  - multiprocess=0.70.14=py310h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=py310h06a4308_0
  - numexpr=2.8.7=py310h286c3b5_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - openai=0.28.1=pyhd8ed1ab_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.1.2=py310h5eee18b_0
  - openssl=3.0.13=h7f8727e_2
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.2=py310h06a4308_0
  - pandas=2.2.1=py310h6a678d5_0
  - pandas-stubs=2.1.4.231227=py310h06a4308_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre2=10.42=hebb0a14_1
  - pillow=10.3.0=py310h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - plotly=5.19.0=py310h2f386ee_0
  - ply=3.11=py310h06a4308_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=5.9.0=py310h5eee18b_0
  - pyarrow=14.0.2=py310h1eedbd7_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py310h5eee18b_1
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py310h5eee18b_0
  - requests=2.31.0=py310h06a4308_1
  - responses=0.13.3=pyhd3eb1b0_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.2=py310ha89cbab_0
  - scikit-image=0.22.0=py310h1128e8f_0
  - scikit-learn=1.4.2=py310h1128e8f_1
  - scipy=1.12.0=py310heeff2f4_0
  - seaborn=0.12.2=py310h06a4308_0
  - sentry-sdk=1.9.0=py310h06a4308_0
  - setproctitle=1.2.2=py310h7f8727e_0
  - setuptools=69.5.1=py310h06a4308_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.45.3=h5eee18b_0
  - tenacity=8.2.2=py310h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2023.4.12=py310h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.15.1=py310h22610ee_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.3.3=py310h5eee18b_0
  - tqdm=4.66.4=py310h2f386ee_0
  - transformers=4.38.2=pyhd8ed1ab_0
  - types-pytz=2022.4.0.0=py310h06a4308_1
  - typing-extensions=4.11.0=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - urllib3=2.2.1=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wandb=0.16.5=pyhd8ed1ab_0
  - wheel=0.43.0=py310h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py310h5eee18b_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - flatbuffers==24.3.25
      - gym==0.26.2
      - gym-notices==0.0.8
      - humanfriendly==10.0
      - jinja2==3.1.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - llvmlite==0.42.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - numba==0.59.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.18.0
      - opencv-python-headless==4.9.0.80
      - platformdirs==4.2.2
      - pooch==1.8.1
      - pygame==2.5.2
      - pymatting==1.1.12
      - python-dotenv==1.0.1
      - referencing==0.35.1
      - rembg==2.0.57
      - rpds-py==0.18.1
      - sympy==1.12
      - torch==2.2.1
      - triton==2.2.0
prefix: /opt/conda/envs/word2world
