name: word2world
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.08.22=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.11=h2bbff1b_2
  - pip=23.2.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - setuptools=68.0.0=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anthropic==0.25.6
    - anyio==4.3.0
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backcall==0.2.0
    - certifi==2023.7.22
    - charset-normalizer==3.3.0
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.1.4
    - contourpy==1.2.0
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - distro==1.9.0
    - exceptiongroup==1.1.3
    - executing==2.0.0
    - filelock==3.13.1
    - flatbuffers==24.3.7
    - fonttools==4.46.0
    - frozenlist==1.4.0
    - fsspec==2024.3.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.21.4
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.34.0
    - imageio-ffmpeg==0.4.9
    - ipykernel==6.26.0
    - ipython==8.16.1
    - jedi==0.19.1
    - jinja2==3.1.3
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.5.0
    - jupyter-core==5.4.0
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - llvmlite==0.42.0
    - markupsafe==2.1.5
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mpmath==1.3.0
    - multidict==6.0.4
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - numba==0.59.0
    - numpy==1.26.1
    - onnxruntime==1.17.1
    - onnxruntime-gpu==1.17.1
    - openai==0.28.1
    - opencv-python-headless==4.9.0.80
    - packaging==23.2
    - pandas==2.2.1
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==10.1.0
    - platformdirs==3.11.0
    - pooch==1.8.1
    - prompt-toolkit==3.0.39
    - protobuf==4.25.3
    - psutil==5.9.6
    - pure-eval==0.2.2
    - pydantic==2.7.0
    - pydantic-core==2.18.1
    - pygame==2.5.2
    - pygments==2.16.1
    - pymatting==1.1.12
    - pyparsing==3.1.1
    - pyreadline3==3.4.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - pytz==2024.1
    - pywin32==306
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - referencing==0.33.0
    - regex==2023.12.25
    - rembg==2.0.55
    - requests==2.31.0
    - rpds-py==0.18.0
    - safetensors==0.4.2
    - scikit-image==0.22.0
    - scipy==1.12.0
    - seaborn==0.13.2
    - six==1.16.0
    - sniffio==1.3.1
    - stack-data==0.6.3
    - sympy==1.12
    - tifffile==2024.2.12
    - tokenizers==0.15.2
    - torch==2.2.1+cu118
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.12.0
    - transformers==4.38.2
    - typing-extensions==4.10.0
    - tzdata==2024.1
    - urllib3==2.0.6
    - wcwidth==0.2.8
    - yarl==1.9.2
